default: &default
  adapter: postgresql
  encoding: utf8
  username:
  password:
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: moment_development

test:
  <<: *default
  database: moment_test

production:
  <<: *default
  database: moment