user = User.create!(username: "ashstpier", password: "password", password_confirmation: "password", email: "user@example.com")

card1 = user.cards.create!(name: "Katie's Hen Do", date: Time.now(), cover_image: File.open(File.join(Rails.root, 'app/assets/images/dummy.jpg')), description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam congue congue sem vitae posuere. Nunc ut imperdiet quam, at semper velit. Integer quis nunc pulvinar, rhoncus est nec, feugiat augue. Praesent non rhoncus neque. Sed ut ultrices enim, ac aliquam sem. Maecenas ac erat ac ante fermentum euismod. Nulla in ultricies nisl. Nullam rutrum volutpat ante, vitae eleifend urna tincidunt sed. Integer fringilla dui massa, vitae dignissim enim rhoncus a. Etiam consectetur posuere maximus.")
card2 = user.cards.create!(name: "Trip to Thailand", date: Time.now(), cover_image: File.open(File.join(Rails.root, 'app/assets/images/dummy.jpg')), description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam congue congue sem vitae posuere. Nunc ut imperdiet quam, at semper velit. Integer quis nunc pulvinar, rhoncus est nec, feugiat augue. Praesent non rhoncus neque. Sed ut ultrices enim, ac aliquam sem. Maecenas ac erat ac ante fermentum euismod. Nulla in ultricies nisl. Nullam rutrum volutpat ante, vitae eleifend urna tincidunt sed. Integer fringilla dui massa, vitae dignissim enim rhoncus a. Etiam consectetur posuere maximus.")
card3 = user.cards.create!(name: "Glastonbury", date: Time.now(), cover_image: File.open(File.join(Rails.root, 'app/assets/images/dummy.jpg')), description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam congue congue sem vitae posuere. Nunc ut imperdiet quam, at semper velit. Integer quis nunc pulvinar, rhoncus est nec, feugiat augue. Praesent non rhoncus neque. Sed ut ultrices enim, ac aliquam sem. Maecenas ac erat ac ante fermentum euismod. Nulla in ultricies nisl. Nullam rutrum volutpat ante, vitae eleifend urna tincidunt sed. Integer fringilla dui massa, vitae dignissim enim rhoncus a. Etiam consectetur posuere maximus.")
card4 = user.cards.create!(name: "Sarah's wedding", date: Time.now(), cover_image: File.open(File.join(Rails.root, 'app/assets/images/dummy.jpg')), description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam congue congue sem vitae posuere. Nunc ut imperdiet quam, at semper velit. Integer quis nunc pulvinar, rhoncus est nec, feugiat augue. Praesent non rhoncus neque. Sed ut ultrices enim, ac aliquam sem. Maecenas ac erat ac ante fermentum euismod. Nulla in ultricies nisl. Nullam rutrum volutpat ante, vitae eleifend urna tincidunt sed. Integer fringilla dui massa, vitae dignissim enim rhoncus a. Etiam consectetur posuere maximus.")
card5 = user.cards.create!(name: "Secret Cinema Star Wars", date: Time.now(), cover_image: File.open(File.join(Rails.root, 'app/assets/images/dummy.jpg')), description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam congue congue sem vitae posuere. Nunc ut imperdiet quam, at semper velit. Integer quis nunc pulvinar, rhoncus est nec, feugiat augue. Praesent non rhoncus neque. Sed ut ultrices enim, ac aliquam sem. Maecenas ac erat ac ante fermentum euismod. Nulla in ultricies nisl. Nullam rutrum volutpat ante, vitae eleifend urna tincidunt sed. Integer fringilla dui massa, vitae dignissim enim rhoncus a. Etiam consectetur posuere maximus.")
card6 = user.cards.create!(name: "Camping with the guys", date: Time.now(), cover_image: File.open(File.join(Rails.root, 'app/assets/images/dummy.jpg')), description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam congue congue sem vitae posuere. Nunc ut imperdiet quam, at semper velit. Integer quis nunc pulvinar, rhoncus est nec, feugiat augue. Praesent non rhoncus neque. Sed ut ultrices enim, ac aliquam sem. Maecenas ac erat ac ante fermentum euismod. Nulla in ultricies nisl. Nullam rutrum volutpat ante, vitae eleifend urna tincidunt sed. Integer fringilla dui massa, vitae dignissim enim rhoncus a. Etiam consectetur posuere maximus.")

card1.location.create!(geojson: "[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[-122.44468688964844,37.72836644908416]},\"properties\":{\"marker-size\":\"large\",\"marker-color\":\"#FF4E50\",\"markerId\":5,\"name\":\"San Fransisco\"}},{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[-122.44573295116425,37.72772153624739]},\"properties\":{\"marker-size\":\"large\",\"marker-color\":\"#FF4E50\",\"markerId\":1,\"name\":\"test\"}}]")